trigger:
  - master

pool:
  vmImage: "macOS-latest"

variables:
  - group: "Terraform Module Variables"

jobs:
  - job:
    displayName: Build and Test
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - script: |
          make install
        displayName: "npm install and link"

      - script: |
          make test
        displayName: "Test module tests"

  - job:
    displayName: Release and Publish
    steps:
      - script: |
          npx semantic-release
        displayName: "Release module"
        env:
          GH_TOKEN: $(GH_TOKEN)
        enabled: false

      - task: Npm@1
        inputs:
          command: "publish"
          publishEndpoint: "NPM alaskaairgroup Organization"
        enabled: false