steps:

  - task: UseNode@1
    inputs:
      version: 14.x

  - task: npmAuthenticate@0
    inputs:
      workingFile: .npmrc
      customEndpoint: NPM alaskaairgroup Organization

  - task: Bash@3
    displayName: Release module
    env:
      GH_TOKEN: $(BOT_GH_TOKEN)
    inputs:
      targetType: inline
      script: |
        npm ci
        npx semantic-release
