steps:
  - task: Bash@3
    displayName: Run generator
    inputs:
      targetType: inline
      script: |
        cp "$(Build.SourcesDirectory)/.yo-rc.json" .
        /usr/bin/yes "" | yo @alaskaairgroup/aag-terraform-module
      workingDirectory: $(Agent.TempDirectory)

  - task: Bash@3
    displayName: Install module prereqs
    inputs:
      targetType: inline
      script: |
        make install
      workingDirectory: $(Agent.TempDirectory)/test-module

  - task: Bash@3
    displayName: Execute module functional tests
    inputs:
      targetType: inline
      script: |
        make test
      workingDirectory: $(Agent.TempDirectory)/test-module

  - task: Bash@3
    displayName: Execute pre-commit hooks tests
    inputs:
      targetType: inline
      script: |
        GOLINT_PATH="$(dirname "$(go list -f {{.Target}} golang.org/x/lint/golint)")"
        export PATH=$PATH:$GOLINT_PATH
        git config user.email "test@example.com"
        git config user.name "Test User"
        git add .
        git commit -m "Initial commit"
      workingDirectory: $(Agent.TempDirectory)/test-module
